---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation for Adevinta Spain SRE Challenge"

Parameters:
  Port:
    Type: Number
    Default: 80
  SubnetA:
    Type: String
  SubnetB:
    Type: String
  SubnetC:
    Type: String
  TargetGroup:
    Type: String
    Default: adevinta-spain-sre-challenge-tg

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: adevinta-spain-sre-challenge-elb
      Type: network
      IpAddressType: ipv4
      Scheme: internal
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
        - !Ref SubnetC
  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref TargetGroup  
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref Port
      Protocol: TCP
